using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;

/// <summary>
/// Generates compile-time navigation constants by reading a TupleExpressionSyntax.
/// </summary>
[Generator]
public class NavigationGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the incremental generator pipeline to observe the Pages property.
    /// </summary>
    /// <param name="context">The context provided by the compiler during initialization.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<Dictionary<string, string>> provider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is PropertyDeclarationSyntax prop && prop.Identifier.Text == "Pages",
            transform: static (ctx, _) => ParseTuple((PropertyDeclarationSyntax)ctx.Node)
        ).Where(static dictionary => dictionary.Count > 0);

        context.RegisterSourceOutput(provider, static (ctx, dictionary) =>
        {
            string generatedCode = GenerateCode(dictionary);
            ctx.AddSource("NavigationConstants.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Extracts named elements and their literal values from the parsed tuple syntax tree.
    /// </summary>
    /// <param name="propertyDeclaration">The property declaration syntax node to parse.</param>
    /// <returns>A dictionary containing tuple element names and string values.</returns>
    static Dictionary<string, string> ParseTuple(PropertyDeclarationSyntax propertyDeclaration)
    {
        Dictionary<string, string> extractedData = [];

        if (propertyDeclaration.ExpressionBody?.Expression is not TupleExpressionSyntax tuple)
        {
            return extractedData;
        }

        foreach (ArgumentSyntax argument in tuple.Arguments)
        {
            if (argument is { NameColon: not null, Expression: LiteralExpressionSyntax literal })
            {
                extractedData[argument.NameColon.Name.Identifier.Text] = literal.Token.ValueText;
            }
        }

        return extractedData;
    }

    /// <summary>
    /// Emits nested static classes and constants based on the extracted tuple items.
    /// </summary>
    /// <param name="navigationEntries">The parsed navigation items containing names and icons.</param>
    /// <returns>The fully constructed C# source code string.</returns>
    static string GenerateCode(Dictionary<string, string> navigationEntries)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Contains compile-time route values and icons for application navigation.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static class NavigationConstants");
        builder.AppendLine("{");

        foreach (KeyValuePair<string, string> entry in navigationEntries)
        {
            string rawName = entry.Key;
            string icon = entry.Value;
            string className = ToPascalCase(rawName);
            string link = $"/{className}";

            builder.AppendLine($$"""
                /// <summary>
                /// Navigation constants for {{rawName}}.
                /// </summary>
                public static class {{className}}
                {
                    public const string Label = "{{rawName}}";
                    public const string Icon = "{{icon}}";
                    public const string Link = "{{link}}";
                }
            """);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// Converts a raw string identifier into PascalCase format suitable for class names.
    /// </summary>
    /// <param name="input">The raw text to convert.</param>
    /// <returns>A formatted PascalCase string.</returns>
    static string ToPascalCase(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
        {
            return string.Empty;
        }

        string[] words = input.Split([' ', '-', '_'], StringSplitOptions.RemoveEmptyEntries);
        StringBuilder builder = new();

        foreach (string word in words)
        {
            if (word.Length == 0)
            {
                continue;
            }

            builder.Append(char.ToUpperInvariant(word[0]));
            if (word.Length > 1)
            {
                builder.Append(word.Substring(1).ToLowerInvariant());
            }
        }

        return builder.ToString();
    }
}